site_name: 实验物理的大数据方法 FAQ
site_description: 'FAQ for Big Data in Experimental Physics'
site_author: 'Teaching Team of Big Data in Experimental Physics'
copyright: 'Copyright &copy; 2020 Teaching Team of Big Data in Experimental Physics, Tsinghua University. All Rights Reserved.'

theme: 
  name: 'material'
  language: 'zh'
  icon:
    logo: material/help
    repo: fontawesome/brands/github
  features:
    - tabs
    - instant

repo_name: 'physics-data/faq'
repo_url: 'https://github.com/physics-data/faq'

extra:
  pagetime: 'on'

nav:
  - 主页: index.md
  - 先修要求: prerequisite.md
  - WSL 环境配置: wsl.md
  - Linux 环境配置: linux.md
  - macOS 环境配置: mac.md
  - Git 使用与配置: git.md
  - 编辑器使用与配置: editor.md
  - 常用命令行工具: tools.md
  - Linux 下的路径: path.md
  - 常见错误信息: error.md
  - GitHub Workflow 配置: workflow.md
  - 常用的软件包的安装方式: install.md
  - 命令行相关问题: command-line.md
  - mail 依赖打环问题: mail.md
  - vitables 无法启动: viewer.md

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
  - git-authors:
      show_contribution: true
      show_line_count: true

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - footnotes
  - def_list
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

